export const tourCards = [
  {
    imageSrc: "/images/topoftthediamond.card.jpg",
    imageAlt: "cards.snowCatTour.imageAlt",
    cardHeader: "cards.snowCatTour.cardHeader",
    cardText: "cards.snowCatTour.cardText",
    linkText: "links.readMore",
    linkHref: "tours/snow-cat",
    duration: "2-3",
    departure: "Arnarstapi",
  },
  {
    imageSrc: "/images/midnightsun.card.jpg",
    imageAlt: "cards.midnightSunTour.imageAlt",
    cardHeader: "cards.midnightSunTour.cardHeader",
    cardText: "cards.midnightSunTour.cardText",
    linkText: "links.readMore",
    linkHref: "tours/midnight-sun",
    duration: "4-5",
    departure: "Arnarstapi",
  },
  {
    imageSrc: "/images/custom_card.png",
    imageAlt: "cards.customTours.imageAlt",
    cardHeader: "cards.customTours.cardHeader",
    cardText: "cards.customTours.cardText",
    linkText: "links.contactUs",
    linkHref: "contactUs/customTours",
    duration: "4-5",
    departure: "Arnarstapi",
  },
  {
    imageSrc: "/images/trodarinn-a-toppnum.jpg",
    imageAlt: "cards.giftCard.imageAlt",
    cardHeader: "cards.giftCard.cardHeader",
    cardText: "cards.giftCard.cardText",
    linkText: "links.contactUs",
    linkHref: "contactUs/giftCard",
    duration: "4-5",
    departure: "Arnarstapi",
  },
];
