name: Deploy GlacierParadise to Netvoktun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }} >> .env
          echo VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }} >> .env
          echo VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }} >> .env
          echo NUXT_EMAIL_HOST=${{ secrets.NUXT_EMAIL_HOST }} >> .env
          echo NUXT_EMAIL_PORT=${{ secrets.NUXT_EMAIL_PORT }} >> .env
          echo NUXT_EMAIL_TO=${{ secrets.NUXT_EMAIL_TO }} >> .env
          echo NUXT_EMAIL_USERNAME=${{ secrets.NUXT_EMAIL_USERNAME }} >> .env
          echo NUXT_EMAIL_PASSWORD=${{ secrets.NUXT_EMAIL_PASSWORD }} >> .env
          echo "!.env" > .git-ftp-include # Add git untracked file
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run generate
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          folder: ./.output/public
